### ISSUE TITLE
How to change UI Langauge?

### ISSUE THREAD

**Issue by khaleeljageer** [yuanbinbinbin/FBReaderImpl#1]
I'm using gradle plugin for reader integration.Currently reader UI has chinese language. Need support for my local language(tamil). How to change the reader language?

**Comment by yuanbinbinbin** [comment]
Hi khaleeljageer，the last version 1.0.1 is supports English、Chinese  but does not include Tamil. if you want to support Tamil ,please  do the following steps

1.   Depending the latest version 
2.   [ Follow this document. ](https://github.com/yuanbinbinbin/FBReaderImpl/blob/master/intro/language/language.md)


If you do, I hope you can share the XML file with me and let the library support more languages. You can either Fork-Pull-Request or via Email(binbinrd@foxmail.com).



Thank you  , good luck.

**Comment by khaleeljageer** [comment]
@yuanbinbinbin Thanks... I could help you on Tamil Localization...

**Comment by khaleeljageer** [comment]
Ta strings added. Verify the pull request [here](https://github.com/yuanbinbinbin/FBReaderImpl/pull/4)
